FROM registry.access.redhat.com/ubi9/ubi:9.5

# Install local rpms
WORKDIR /tmp/rpms
COPY rpms .
RUN rpm -i --nodeps *.rpm

# Install wkhtmltopdf and wkhtmltoimage
RUN dnf install -y wget \
    libXrender \
    libXext \
    fontconfig  && \
    wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox-0.12.6.1-3.almalinux9.x86_64.rpm && \
    dnf install -y ./wkhtmltox-0.12.6.1-3.almalinux9.x86_64.rpm && \
    rm ./wkhtmltox-0.12.6.1-3.almalinux9.x86_64.rpm

# Install system dependencies and Microsoft ODBC Driver 18 for SQL Server
RUN dnf install -y \
    wget \
    git \
    unixODBC \
    unixODBC-devel && \
    curl -sSL https://packages.microsoft.com/config/rhel/9/prod.repo -o /etc/yum.repos.d/mssql-release.repo && \
    ACCEPT_EULA=Y dnf install -y msodbcsql18 && \
    dnf clean all

# Install Miniconda
RUN mkdir -p ~/miniconda3 && \
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh && \
    bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3 && \
    rm ~/miniconda3/miniconda.sh && \
    ~/miniconda3/bin/conda update -n base -c defaults conda -y

# Update working directory
WORKDIR /app
RUN rm -rf /tmp/rpms

# Copy environment file and create Conda environment
COPY environment.yaml .
RUN ~/miniconda3/bin/conda env create -f /app/environment.yaml

# Copy application files and folders
COPY app.py .
COPY assets ./assets
COPY llm ./llm
COPY utils ./utils
COPY scheduler ./scheduler
COPY vector_db ./vector_db
COPY generator ./generator
COPY ui ./ui
COPY entrypoint.sh .

# Set permissions and switch to non-root user
RUN chmod -R 777 . && \
    chown 1001:0 ./*

USER 1001

EXPOSE 7860
EXPOSE 8000

CMD ./entrypoint.sh
