FROM registry.access.redhat.com/ubi9/python-312:9.5

WORKDIR /opt/app-root/src

USER root

COPY rpms/ ./rpms/

RUN cd rpms && rpm -i --nodeps *.rpm

RUN dnf install -y wget \
    libXrender \
    libXext \
    fontconfig  && \
    wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox-0.12.6.1-3.almalinux9.x86_64.rpm && \
    dnf install -y ./wkhtmltox-0.12.6.1-3.almalinux9.x86_64.rpm && \
    rm ./wkhtmltox-0.12.6.1-3.almalinux9.x86_64.rpm

RUN dnf install -y \
    unixODBC \
    unixODBC-devel && \
    curl -sSL https://packages.microsoft.com/config/rhel/9/prod.repo -o /etc/yum.repos.d/mssql-release.repo && \
    ACCEPT_EULA=Y dnf install -y msodbcsql18 && \
    dnf clean all

WORKDIR /opt/app-root/src

RUN rm -rf rpms

USER 1001

COPY --chown=1001:0 requirements.txt ./

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    rm -f requirements.txt && \
        chmod -R g+w /opt/app-root/lib/python3.12/site-packages && \
    fix-permissions /opt/app-root -P

COPY --chown=1001:0 app.py ./
COPY --chown=1001:0 assets/ ./assets/
COPY --chown=1001:0 llm/ ./llm/
COPY --chown=1001:0 utils/ ./utils/
COPY --chown=1001:0 scheduler/ ./scheduler/
COPY --chown=1001:0 vector_db/ ./vector_db/
COPY --chown=1001:0 generator/ ./generator/
COPY --chown=1001:0 ui/ ./ui/

EXPOSE 7860
EXPOSE 8000

CMD ["python", "app.py"]
