name: llm-on-openshift
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - aiohttp==3.11.18
    - gradio==5.29.0
    - hf-xet==1.1.1
    - httpx==0.28.1
    - langchain-community==0.3.24
    - langchain-core==0.3.59
    - langchain-elasticsearch==0.3.2
    - langchain-huggingface==0.2.0
    - langchain-openai==0.3.16
    - langchain-postgres==0.0.14
    - langchain-sqlserver==0.1.1
    - langchain==0.3.25
    - Markdown==3.8
    - openai==1.78.1
    - pandas==2.2.3
    - pdfkit==1.0.0
    - prometheus-client==0.21.1
    - psycopg[binary]==3.2.9
    - pydantic==2.11.4
    - pyodbc==5.2.0
    - PyYAML==6.0.2
    - redis==6.1.0
    - requests==2.32.3
    - sentence-transformers==4.1.0
    - text-generation==0.7.0
