name: llm-on-openshift
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - accelerate
  - aiofiles
  - aiohttp
  - aiosignal
  - altair
  - annotated-types
  - anyio
  - async-timeout
  - attrs
  - certifi
  - charset-normalizer
  - click
  - cmake
  - contourpy
  - cycler
  - dataclasses-json
  - faiss-cpu
  - fastapi
  - ffmpy
  - filelock
  - fonttools
  - frozenlist
  - fsspec
  - greenlet
  - h11
  - httpcore
  - httpx
  - idna
  - importlib-resources
  - itsdangerous
  - jinja2
  - joblib
  - jsonpatch
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - kiwisolver
  - lit
  - markdown
  - markupsafe
  - marshmallow
  - matplotlib
  - mpmath
  - multidict
  - networkx
  - nltk
  - numpy
  - orjson
  - packaging
  - pandas
  - pgvector
  - pillow
  - pip
  - psycopg
  - pydantic
  - pydantic-core
  - pydub
  - pyodbc
  - pyparsing
  - python-dateutil
  - python-dotenv
  - python-multipart
  - pytz
  - pyyaml
  - redis
  - referencing
  - regex
  - requests
  - rpds-py
  - ruff
  - safetensors
  - scikit-learn
  - scipy
  - sentence-transformers
  - sentencepiece
  - six
  - sniffio
  - sqlalchemy
  - starlette
  - sympy
  - tenacity
  - threadpoolctl
  - tokenizers
  - toolz
  - torchvision
  - tqdm
  - transformers
  - triton
  - typing-extensions
  - tzdata
  - urllib3
  - uvicorn
  - websockets
  - yarl
  - pip:
    - gradio
    - gradio-client
    - huggingface-hub
    - langchain
    - langchain-community
    - langchain-core
    - langchain-elasticsearch
    - langchain-openai
    - langchain-sqlserver
    - langchain-text-splitters
    - langsmith
    - mypy-extensions
    - pdfkit
    - prometheus-client
    - semantic-version
    - text_generation
    - torch
    - typing-inspect
